#!/usr/bin/env bash
#
# Run cmd/cigocacher based on the revision pinned in tool/cigocacher.rev

set -euo pipefail

goos() {
    case "${OSTYPE}" in
        linux*)
            echo "linux"
            ;;
        darwin*)
            echo "darwin"
            ;;
        mingw*|msys*|cygwin*)
            echo "windows"
            ;;
        *)
            echo "unknown"
            ;;
    esac
}

goarch() {
    local machine="$(uname -m)"
    case "$machine" in
        x86_64|amd64)
            echo "amd64"
            ;;
        aarch64|arm64)
            echo "arm64"
            ;;
        armv7l|armv6l)
            echo "arm"
            ;;
        i386|i686)
            echo "386"
            ;;
        *)
            echo "$machine"
            ;;
    esac
}

if [[ "${CI:-}" == "true" ]]; then
    set -x
fi

cachedir="${HOME}/.cache/tailscale-cigocacher"

(
    time {
        if [[ "${CI:-}" == "true" ]]; then
            set -x
        fi

        SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
        repo_root="${SCRIPT_DIR}/../"
        cd "$repo_root"

        tarball="${cachedir}.tar.gz"

        want_rev="$(cat ./tool/cigocacher.rev)"
        got_rev=""
        if [[ -x "${cachedir}/cigocacher" ]]; then
            got_rev=$("${cachedir}/cigocacher" --version)
        fi
    }

    if [[ "$want_rev" != "$got_rev" ]]; then
        time rm -rf "$cachedir" "$tarball"
        time mkdir -p "$cachedir"
        time platform="$(goos)-$(goarch)"
        time curl -w "%{size_download} bytes | %{time_total}s | %{speed_download} bytes/sec\n" -fsSL -o "$tarball" \
            "https://github.com/tomhjp/temp-tailscale-fork/releases/download/cmd%2Fcigocacher%2F${want_rev}/cigocacher-${platform}.tar.gz"
        time (cd "$cachedir" && tar -xf "$tarball")
        time rm -f "$tarball"
    fi
)

exec "${cachedir}/cigocacher" "$@"
